spring.application.name=springBootTest
spring.profiles.active=dev

# ===== 日志 =====
logging.level.root=info
logging.level.com.fenglin.springboottest=info
logging.file.name=log/xx.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss}  %level %logger{50}.%M %L:%m%n
